# Type Name              ID GECOS                         Home                  Shell
g pulse-agent-admin      -  -                             -                     -
u pulse-agent            -  "Pulse Agent service account" /var/lib/pulse-agent /usr/sbin/nologin
m pulse-agent            docker
